name = "Stella"
uuid = "b1cd83c4-5688-5aa2-8927-7445e86cd0e2"
version = "v0.2.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
FreqTools = "fb344015-2583-4870-9d87-af59fc8caa54"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Survival = "8a913413-2070-5976-9d4c-2b364fdc2f7f"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ReadStat = "d71aba96-b539-5138-91ee-935c3ee1374c"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
TableMetadataTools = "9ce81f87-eacc-4366-bf80-b621a3098ee2"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ROCAnalysis = "f535d66d-59bb-5153-8d2b-ef0a426c6aff"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
LogisticROC = "6bf4ee07-1766-4a3a-9e7e-3ffe73513617"
StataIO = "4250fffb-2d87-4dab-9cf8-12ba0ef8cdb9"
AnalysisOfVariance = "01c9c671-d471-43d2-8b89-3af15e6b824d" 

[compat]
julia = "1.6"
DataFrames = "1"
CategoricalArrays = "1"
DataStructures = "0"
FreqTools = "0"
FreqTables = "0,1,2"
GLM = "0,1"
HypothesisTests = "0"
NamedArrays = "0,1"
PyCall = "0,1"
StatsBase = "0"
StatFiles = "0,1"
TableMetadataTools = "0"
LogisticROC = "0"
Dates= "1"
AnalysisOfVariance = "0"
DataAPI = "0,1"
Distributions = "0,1"
Survival = "0,1"
Glob = "0,1"
LinearAlgebra = "1"
Printf = "1"
StatIO = "0"
Statistics = "0,1"
PrettyTables = "0,1,2,3"
JLD2 = "0"
TableMetadataTools = "0"
Reexport = "0,1"
ROCAnalysis = "0"
Plots = "0,1"
LogisticROC = "0"

[extras]

[targets]


